import{a as d,S as $,i as a}from"./assets/vendor-CVWx-W0A.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&c(s)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();const M="56192086-83055f2d7d7b11f9b3a937a1d";d.defaults.baseURL="https://pixabay.com/api/";async function u(o,e){return(await d.get("",{params:{key:M,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15}})).data}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),h=document.querySelector(".load-more"),P=new $(".gallery a",{captionsData:"alt",captionDelay:250});function g(o){const e=o.map(({webformatURL:n,largeImageURL:c,tags:t,likes:r,views:s,comments:v,downloads:q})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${c}">
          <img class="gallery-image" src="${n}" alt="${t}" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b>${r}</p>
          <p class="info-item"><b>Views</b>${s}</p>
          <p class="info-item"><b>Comments</b>${v}</p>
          <p class="info-item"><b>Downloads</b>${q}</p>
        </div>
      </li>
    `).join("");f.insertAdjacentHTML("beforeend",e),P.refresh()}function B(){f.innerHTML=""}function p(){m.classList.remove("is-hidden")}function y(){m.classList.add("is-hidden")}function b(){h.classList.remove("is-hidden")}function L(){h.classList.add("is-hidden")}const w=document.querySelector(".search-form"),R=document.querySelector(".load-more");let l="",i=1;const S=15;w.addEventListener("submit",O);R.addEventListener("click",H);async function O(o){if(o.preventDefault(),l=o.currentTarget.elements.searchQuery.value.trim(),!l){a.warning({message:"Please enter a search query!",position:"topRight"});return}i=1,B(),L(),p();try{const e=await u(l,i);if(e.hits.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(e.hits),e.totalHits>S&&b()}catch(e){a.error({message:`Something went wrong: ${e.message}`,position:"topRight"})}finally{y(),w.reset()}}async function H(){i+=1,L(),p();try{const o=await u(l,i);g(o.hits),x();const e=Math.ceil(o.totalHits/S);i>=e?a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):b()}catch(o){a.error({message:`Something went wrong: ${o.message}`,position:"topRight"})}finally{y()}}function x(){const o=document.querySelector(".gallery-item");if(o){const{height:e}=o.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
